### PR TITLE
Created missing stories for PSCourse Pages

### LINKED ISSUE #16: FEATURE: Add missing stories for Course Pages
- [x] Create story for PSCourseCreatePage
- [x] Create story for PSCourseIndexPage
- [x] Create story for CourseTable

### PR DESCRIPTION
**Pull request by chloeqta**
EDIT: I also created CourseTable.stories.js so CourseTable stories can be viewed.
Screenshot 2024-03-04 at 4 43 12 PM

In this PR, I found that existing PSCourse Pages files were missing their corresponding stories. I created PSCourseCreatePage.stories.js and PSCourseIndexPage.stories.js so that future modifications can be made and viewed on storybook.

Closes #16.

Screenshot 2024-02-28 at 3 20 17 PM
Screenshot 2024-02-28 at 3 20 43 PM

### CODE REVIEW

**Review by bwr02 — DISMISSED** [review]
LGTM
link to github sotrybook: https://ucsb-cs156-w24.github.io/proj-courses-w24-5pm-3/prs/17/storybook/?path=/docs/pages-courses-pscoursecreatepage--default

**Review by sophiattran — DISMISSED** [review]
lgtm

**Review by tallyhawley — APPROVED** [review]
LGTM

**Review by tallyhawley — DISMISSED** [review]
Can you add some fixtures & stories for an IndexPage containing multiple PSCourses?

EDIT:
Rather than modifiying the IndexPage story, please add a story for the CourseTable component.

**Review by sophiattran — APPROVED** [review]
lgtm!

**Review by theanimated01 — APPROVED** [review]
lgtm

**Review by bwr02 — APPROVED** [review]
LGTM

**Review by tallyhawley — APPROVED** [review]
Looks great! Thank you for adding these :)

**Pull request merged**
