### PR TITLE
Removed unnecessary exclamation point

### PR DESCRIPTION
**Pull request by Shakcmpsc**
Removed unnecessary exclamation point

#2
Screenshot 2024-03-03 at 5 44 23 PM

Screenshot 2024-03-03 at 5 43 58 PM

### CODE REVIEW

**Review by bwr02 — APPROVED** [review]
LGTM

**Review by sophiattran — APPROVED** [review]
lgtm

**Review by tallyhawley — CHANGES_REQUESTED** [review]
Please provide some before/after screenshots & a link to your dev Dokku deployment showing the changes!

**Review by tallyhawley — APPROVED** [review]
:shipit:

**Pull request merged**
